name: "Let's build from here"

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "24.10.5"
            target: "x86"
            subtarget: "64"
            sdk_name: "immortalwrt-sdk-24.10.5-x86-64_gcc-13.3.0_musl.Linux-x86_64"
            ext: "ipk"
          - version: "25.12-SNAPSHOT"
            target: "x86"
            subtarget: "64"
            sdk_name: "immortalwrt-sdk-25.12-SNAPSHOT-x86-64_gcc-14.3.0_musl.Linux-x86_64"
            ext: "apk"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        uses: mokanove/mokanove/actions/luci-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          version: ${{ matrix.version }}
          target: ${{ matrix.target }}
          subtarget: ${{ matrix.subtarget }}
          sdk_name: ${{ matrix.sdk_name }}

      - name: Clone Project source code
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/
          git clone https://github.com/mokanove/luci-app-powermanager.git

      - name: Get Version
        id: get_version
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/luci-app-powermanager
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build!
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}
          make package/luci-app-powermanager/compile V=s -j$(nproc)

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ matrix.sdk_name }}/bin/packages/*/*/*.${{ matrix.ext }}
          body: |
            # This release by GitHub Actions
            > Do you need know new update? Do it your self!
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
